workflows: 
  version: 2
  build: 
    triggers:
      - schedule:
          cron: "* * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - check_versions

  upload: 
    jobs:
      - release_version
                
jobs:
  check_versions:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
          fingerprints:
            - "a3:d9:43:78:51:ab:b7:21:5a:eb:de:35:4d:00:8e:83"
      - checkout
      - run: 
          name: Get lastest stable Jenkins WAR
          command: wget -nv http://mirrors.jenkins-ci.org/war-stable/latest/jenkins.war
      - run: 
          name: Get JFrog CLI
          command: curl -fL https://getcli.jfrog.io | sh
      
  release_version:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
          fingerprints:
            - "a3:d9:43:78:51:ab:b7:21:5a:eb:de:35:4d:00:8e:83"
      - checkout 
